### Essential NumPy and Pandas Functions for Data Analysis

Let's look at practical code snippets that demonstrate the most useful NumPy and pandas methods for data analysis in Python. You can use these in a Jupyter notebook for experimentation and workflow mastery.

#### NumPy Basics for Data Analysis
Import NumPy:

In [29]:
import numpy as np

1. Creating Arrays

In [30]:
arr = np.array([1, 2, 3, 4])            # 1D array
matrix = np.array([[1, 2], [3, 4]])     # 2D array
zeros = np.zeros((2, 3))                # 2x3 array of zeros
ones = np.ones((2, 3))                  # 2x3 array of ones
rnd = np.random.rand(2, 3)              # 2x3 array of random floats

2. Array Shape, Reshape, Flatten

In [31]:
print(arr.shape)                # (4,)
reshaped = matrix.reshape((4, 1))   # Reshape to 4 rows, 1 column
flat = matrix.ravel()               # Flatten to 1D array

(4,)


3. Indexing and Slicing

In [32]:
print(matrix[0, 1])    # element at first row, second column
print(arr[1:3])        # slice elements 1 to 2

2
[2 3]


4. Basic Math Operations

In [33]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)           # [11 22 33]
print(a - b)           # [ 9 18 27]
print(a * b)           # [10 40 90]
print(a / b)           # [10. 10. 10.]


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


5. Aggregation and Stats

In [34]:
np.sum(arr)                 # 10
np.mean(arr)                # 2.5
np.std(arr)                 # Standard deviation
np.min(arr), np.max(arr)    # Min and max values

(np.int64(1), np.int64(4))

6. Dot Product, Matrix Ops

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)          # 1*4 + 2*5 + 3*6 = 32
mat = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matprod = np.matmul(mat, mat2) # Matrix multiplication

7. Logical and Filtering

In [36]:
arr[arr > 2]                # Returns [3, 4]
np.where(arr > 2)           # Indices where condition is true

(array([2, 3]),)

8. Random Sampling

In [37]:
np.random.randint(0, 100, size=5) # 5 random ints 0-99
np.random.choice([0, 1], size=10) # 10 random 0s or 1s

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 1])

#### Pandas Basics for Data Analysis
Import pandas:

In [38]:
import pandas as pd

1. Creating DataFrames

In [39]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data) # Create DataFrame

2. Inspecting Data

In [40]:
df.head()                # First 5 rows
df.tail(3)                # Last 3 rows
df.info()                 # DataFrame info + datatypes
df.describe()             # Summary statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

3. Selecting Data

In [41]:
df['A']                   # Get column A
df.loc[0]                 # Row by label (index 0)
df.iloc[1:3]              # Rows 1-2 by position
df[df['A'] > 1]           # Filter rows where A > 1

A  B
1  2  5
2  3  6

4. Adding/Dropping Columns

In [42]:
df['C'] = df['A'] + df['B']     # Add new column
new_df = df.drop('B', axis=1)   # Drop column B

5. Missing Values & Types

In [43]:
df.isnull().sum()               # Missing values per column
df.fillna(0)                    # Replace NaNs with 0
df['A'] = df['A'].astype(float) # Change column type

6. Grouping and Aggregation

In [44]:
grouped = df.groupby('A').sum()   # Sum columns, grouped by values in A
df['A'].value_counts()            # Count unique values in A

A
1.0    1
2.0    1
3.0    1
Name: count, dtype: int64

7. Sorting

In [45]:
df.sort_values('B', ascending=False)  # Sort by column B

A  B  C
2  3.0  6  9
1  2.0  5  7
0  1.0  4  5

8. Reading/Writing Files

In [46]:
df.to_csv('mydata.csv') # Save to CSV
df = pd.read_csv('mydata.csv') # Load from CSV
df.head()

Unnamed: 0    A  B  C
0           0  1.0  4  5
1           1  2.0  5  7
2           2  3.0  6  9

9. Apply/Map Functions

In [47]:
df['A_squared'] = df['A'].apply(lambda x: x**2) # Apply to column
df['B_label'] = df['B'].map({4: 'Low', 5: 'Med', 6: 'High'}) # Map values
df.sample(3)

Unnamed: 0    A  B  C  A_squared B_label
1           1  2.0  5  7        4.0     Med
2           2  3.0  6  9        9.0    High
0           0  1.0  4  5        1.0     Low

### Task:

- Generated a Synthetic Dataset with columns of `age`, `salary`, `department`, `years_experience`, and `is_manager`.

In [48]:
np.random.seed(42) # For reproducibility
n_samples = 100 # Number of samples

data = {
    'age': np.random.randint(18, 60, size=n_samples),
    'salary': np.random.randint(30000, 120000, size=n_samples),
    'department': np.random.choice(['IT', 'HR', 'Finance', 'Marketing'], size=n_samples),
    'years_experience': np.round(np.random.normal(5, 2, size=n_samples), 1),
    'is_manager': np.random.choice([0, 1], size=n_samples)
}
df = pd.DataFrame(data)

Q1. View data structure

In [49]:
df.shape
df.dtypes
df.head(10)

age  salary department  years_experience  is_manager
0   56   38392         IT              -0.8           0
1   46   60535  Marketing               3.4           1
2   32  108603         HR               5.0           1
3   25   82256         HR               4.2           1
4   38  119135         HR               4.1           1
5   56   65222    Finance               2.8           0
6   36  107373    Finance               6.7           1
7   40  109575  Marketing               6.9           0
8   28  114651  Marketing               5.8           1
9   28   93335         IT               1.2           1

Q2. Get DataFrame Info and Summary Stats

In [50]:
df.info()
df.describe(include='all').transpose()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               100 non-null    int64  
 1   salary            100 non-null    int64  
 2   department        100 non-null    object 
 3   years_experience  100 non-null    float64
 4   is_manager        100 non-null    int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 4.0+ KB


count unique        top freq      mean           std  \
age               100.0    NaN        NaN  NaN     37.91     12.219454   
salary            100.0    NaN        NaN  NaN  77809.16  26058.643576   
department          100      4  Marketing   36       NaN           NaN   
years_experience  100.0    NaN        NaN  NaN     4.823      2.237822   
is_manager        100.0    NaN        NaN  NaN      0.47      0.501614   

                      min      25%      50%       75%       max  
age                  18.0    26.75     38.0     46.25      59.0  
salary            30206.0  55141.0  80932.0  98107.25  119474.0  
department            NaN      NaN      NaN       NaN       NaN  
years_experience     -0.8    3.475      4.7       6.0      11.4  
is_manager            0.0      0.0      0.0       1.0       1.0

Q3. Do Simple Numpy Operations

In [51]:
ages = df['age'].to_numpy()
salaries = df['salary'].to_numpy()
years = df['years_experience'].to_numpy()

np.mean(ages), np.median(ages), np.std(ages)
np.mean(salaries), np.median(salaries), np.std(salaries)
np.dot(ages[:5], salaries[:5])
np.random.randint(0,100,5)

array([83, 88, 85, 12, 58])

Q4. Filtering and Indexing Rows

In [52]:
df[df['age'] > 30].head()
df[df['is_manager'] == 1].head()
df[(df['age']>30) & (df['is_manager']==1)].head()
df.loc[0]
df.iloc[1:3]

age  salary department  years_experience  is_manager
1   46   60535  Marketing               3.4           1
2   32  108603         HR               5.0           1

Q5. Adding a Column

In [53]:
df['years_exp_nonzero'] = df['years_experience'].apply(lambda x: x if x > 0 else 0.5)
df['salary_per_year_exp'] = (df['salary'] / df['years_exp_nonzero']).round(2)
df.head()

age  salary department  years_experience  is_manager  years_exp_nonzero  \
0   56   38392         IT              -0.8           0                0.5   
1   46   60535  Marketing               3.4           1                3.4   
2   32  108603         HR               5.0           1                5.0   
3   25   82256         HR               4.2           1                4.2   
4   38  119135         HR               4.1           1                4.1   

   salary_per_year_exp  
0             76784.00  
1             17804.41  
2             21720.60  
3             19584.76  
4             29057.32

Q6. Grouping and Aggregation

In [54]:
df.groupby('department')['salary'].mean()

department
Finance      83124.708333
HR           73523.052632
IT           75825.476190
Marketing    77684.722222
Name: salary, dtype: float64